import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

const AnalysisPage = () => {
    const navigate = useNavigate();
    const [selectedFile, setSelectedFile] = useState(null);
    const [isAnalyzing, setIsAnalyzing] = useState(false);
    const [violations, setViolations] = useState([]);
    const [analysisComplete, setAnalysisComplete] = useState(false);
    const fileInputRef = React.useRef(null);

    const handleFileSelect = (e) => {
        const file = e.target.files?.[0];
        if (file) {
            // Validate file type
            const validTypes = ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'];
            if (validTypes.includes(file.type)) {
                setSelectedFile(file);
                setViolations([]);
                setAnalysisComplete(false);
            } else {
                alert('Please upload a PDF or DOC/DOCX file');
            }
        }
    };

    const handleAnalyze = async () => {
        if (!selectedFile) return;

        setIsAnalyzing(true);
        try {
            // TODO: Implement document parsing and rule-based analysis here
            // This will be connected to documentParser.js and ruleEngine.js
            
            // Simulated delay for demo
            await new Promise(resolve => setTimeout(resolve, 2000));

            // TODO: Replace with actual analysis results
            const mockViolations = [
                {
                    id: 1,
                    type: 'Passive Voice',
                    message: 'Avoid passive voice. Consider using active voice.',
                    line: 5,
                    text: 'The report was generated by the system',
                    suggestion: 'The system generated the report'
                },
                {
                    id: 2,
                    type: 'Long Sentence',
                    message: 'Sentence is too long. Break it into shorter sentences.',
                    line: 12,
                    text: 'This is a very long sentence that contains multiple clauses...',
                    suggestion: 'Break into 2-3 shorter sentences'
                }
            ];

            setViolations(mockViolations);
            setAnalysisComplete(true);
        } catch (error) {
            alert('Error analyzing document: ' + error.message);
        } finally {
            setIsAnalyzing(false);
        }
    };

    const handleDownloadReport = () => {
        // TODO: Implement PDF/CSV download functionality
        alert('Download functionality will be implemented');
    };

    const handleStartOver = () => {
        setSelectedFile(null);
        setViolations([]);
        setAnalysisComplete(false);
        if (fileInputRef.current) {
            fileInputRef.current.value = '';
        }
    };

    const handleBackHome = () => {
        navigate('/');
    };

    return (
      <div className="min-h-screen bg-gradient-to-br from-[#000028] to-slate-800 p-8">
        <div className="max-w-4xl mx-auto ">
          {/* Header */}
          <div className="mb-12 flex gap-6 items-start">
            <button
              onClick={handleBackHome}
              className="text-slate-400 hover:text-white transition text-2xl mt-1 cursor-pointer"
              title="Back to Home"
            >
              ←
            </button>
            <div>
              <h1 className="text-4xl font-bold text-white mb-2">
                Document Analysis
              </h1>
              <p className="text-slate-400">
                Upload your document to identify editorial violations
              </p>
            </div>
          </div>

          {!analysisComplete ? (
            // Upload Section
            <div className="bg-[#000028] rounded-lg shadow-xl p-8 border border-[#009999]">
              <div className="text-center mb-8">
                <div className="text-6xl mb-4">📑</div>
                <h2 className="text-2xl font-semibold text-white mb-2">
                  Upload Your Document
                </h2>
                <p className="text-slate-400">Supported formats: PDF</p>
              </div>

              {/* File Upload Area */}
              <div
                className="border-2 border-dashed border-slate-600 rounded-lg p-12 text-center hover:border-[#009999] transition cursor-pointer"
                onClick={() => fileInputRef.current?.click()}
              >
                {selectedFile ? (
                  <div>
                    <p className="text-white font-semibold mb-2">
                      ✓ Selected File
                    </p>
                    <p className="text-slate-400">{selectedFile.name}</p>
                    <p className="text-slate-500 text-sm mt-2">
                      ({(selectedFile.size / 1024).toFixed(2)} KB)
                    </p>
                  </div>
                ) : (
                  <div>
                    <p className="text-white font-semibold mb-2">
                      Click to upload or drag and drop
                    </p>
                    <p className="text-slate-400 text-sm">
                      PDF or DOC files up to 10MB
                    </p>
                  </div>
                )}
              </div>

              <input
                ref={fileInputRef}
                type="file"
                accept=".pdf,.doc,.docx"
                onChange={handleFileSelect}
                className="hidden"
              />

              {/* Action Buttons */}
              <div className="flex gap-4 mt-8">
                <button
                  onClick={handleAnalyze}
                  disabled={!selectedFile || isAnalyzing}
                  className="flex-1 bg-[#005d5d] hover:bg-[#009999] disabled:bg-slate-700 disabled:cursor-not-allowed text-white font-semibold py-3 px-6 rounded-lg transition duration-200"
                >
                  {isAnalyzing ? "Analyzing..." : "Analyze Document"}
                </button>
                {selectedFile && (
                  <button
                    onClick={handleStartOver}
                    className="flex-1 bg-slate-700 hover:bg-slate-600 text-white font-semibold py-3 px-6 rounded-lg transition duration-200"
                  >
                    Clear
                  </button>
                )}
              </div>
            </div>
          ) : (
            // Results Section
            <div className="bg-slate-800 rounded-lg shadow-xl p-8 border border-slate-700">
              {/* Summary Stats */}
              <div className="grid grid-cols-3 gap-6 mb-8">
                <div className="bg-slate-700 rounded-lg p-6 text-center">
                  <p className="text-slate-400 text-sm mb-2">
                    Total Violations
                  </p>
                  <p className="text-3xl font-bold text-red-400">
                    {violations.length}
                  </p>
                </div>
                <div className="bg-slate-700 rounded-lg p-6 text-center">
                  <p className="text-slate-400 text-sm mb-2">File Analyzed</p>
                  <p className="text-lg font-semibold text-white truncate">
                    {selectedFile?.name}
                  </p>
                </div>
                <div className="bg-slate-700 rounded-lg p-6 text-center">
                  <p className="text-slate-400 text-sm mb-2">
                    Compliance Score
                  </p>
                  <p className="text-3xl font-bold text-green-400">
                    {violations.length === 0 ? "100%" : "70%"}
                  </p>
                </div>
              </div>

              {/* Violations List */}
              {violations.length > 0 ? (
                <div className="mb-8">
                  <h3 className="text-xl font-semibold text-white mb-4">
                    Detected Violations
                  </h3>
                  <div className="space-y-4">
                    {violations.map((violation) => (
                      <div
                        key={violation.id}
                        className="bg-red-900 bg-opacity-20 border border-red-700 rounded-lg p-4"
                      >
                        <div className="flex justify-between items-start mb-2">
                          <p className="text-red-300 font-semibold">
                            {violation.type}
                          </p>
                          <p className="text-slate-400 text-sm">
                            Line {violation.line}
                          </p>
                        </div>
                        <p className="text-slate-300 text-sm mb-3">
                          "{violation.text}"
                        </p>
                        <div className="bg-slate-900 rounded p-3">
                          <p className="text-slate-400 text-xs mb-1">
                            Suggestion:
                          </p>
                          <p className="text-green-300">
                            {violation.suggestion}
                          </p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ) : (
                <div className="text-center py-8">
                  <p className="text-green-400 text-lg font-semibold">
                    ✓ No violations found!
                  </p>
                  <p className="text-slate-400 mt-2">
                    Your document is well-written
                  </p>
                </div>
              )}

              {/* Download Section */}
              <div className="border-t border-slate-700 pt-8 mb-8">
                <h3 className="text-lg font-semibold text-white mb-4">
                  Export Report
                </h3>
                <div className="flex gap-4">
                  <button
                    onClick={handleDownloadReport}
                    className="flex-1 bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-6 rounded-lg transition duration-200"
                  >
                    📥 Download PDF
                  </button>
                  <button
                    onClick={handleDownloadReport}
                    className="flex-1 bg-green-600 hover:bg-green-700 text-white font-semibold py-3 px-6 rounded-lg transition duration-200"
                  >
                    📊 Export CSV
                  </button>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex gap-4">
                <button
                  onClick={handleStartOver}
                  className="flex-1 bg-slate-700 hover:bg-slate-600 text-white font-semibold py-3 px-6 rounded-lg transition duration-200"
                >
                  Analyze Another Document
                </button>
                <button
                  onClick={handleBackHome}
                  className="flex-1 bg-slate-700 hover:bg-slate-600 text-white font-semibold py-3 px-6 rounded-lg transition duration-200"
                >
                  Back to Home
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    );
};

export default AnalysisPage;
