import React from 'react'
import { useNavigate } from 'react-router-dom';

const GeneratedReport = () => {
    const navigate = useNavigate();

    const handleStartNewAnalysis = () => {
        navigate('/');
    };

    const handleBackToChat = () => {
        navigate('/analyze');
    };

    const handleDownloadPDF = () => {
        // PDF download logic to be implemented
        alert('PDF download functionality will be implemented');
    };

    const handleDownloadCSV = () => {
        // CSV download logic to be implemented
        alert('CSV download functionality will be implemented');
    };

    return (
        <>
            <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-800 p-8">
                    <div className="max-w-4xl mx-auto">
                            {/* Header */}
                            <div className="mb-12">
                                    <h1 className="text-4xl font-bold text-white mb-2">Compliance Report</h1>
                                    <p className="text-slate-400">Review and download your document analysis results</p>
                            </div>

                            {/* Report Card */}
                            <div className="bg-slate-800 rounded-lg shadow-xl p-8 mb-8 border border-slate-700">
                                    {/* Report Summary */}
                                    <div className="grid grid-cols-3 gap-6 mb-8">
                                            <div className="bg-slate-700 rounded-lg p-6 text-center">
                                                    <p className="text-slate-400 text-sm mb-2">Total Violations</p>
                                                    <p className="text-3xl font-bold text-red-400">12</p>
                                            </div>
                                            <div className="bg-slate-700 rounded-lg p-6 text-center">
                                                    <p className="text-slate-400 text-sm mb-2">Critical Issues</p>
                                                    <p className="text-3xl font-bold text-orange-400">5</p>
                                            </div>
                                            <div className="bg-slate-700 rounded-lg p-6 text-center">
                                                    <p className="text-slate-400 text-sm mb-2">Compliance Score</p>
                                                    <p className="text-3xl font-bold text-green-400">68%</p>
                                            </div>
                                    </div>

                                    {/* Violations List */}
                                    <div className="mb-8">
                                            <h2 className="text-xl font-semibold text-white mb-4">Detected Violations</h2>
                                            <div className="space-y-3">
                                                    <div className="bg-red-900 bg-opacity-20 border border-red-700 rounded-lg p-4">
                                                            <p className="text-red-300 font-semibold">Passive Voice Usage</p>
                                                            <p className="text-slate-300 text-sm mt-1">Line 45: "The report was generated by the system" - Use active voice for clarity</p>
                                                    </div>
                                                    <div className="bg-orange-900 bg-opacity-20 border border-orange-700 rounded-lg p-4">
                                                            <p className="text-orange-300 font-semibold">Indefinite Article Misuse</p>
                                                            <p className="text-slate-300 text-sm mt-1">Line 12: "a user" should be "an user" - Incorrect vowel usage</p>
                                                    </div>
                                                    <div className="bg-orange-900 bg-opacity-20 border border-orange-700 rounded-lg p-4">
                                                            <p className="text-orange-300 font-semibold">Article Usage Error (a vs an)</p>
                                                            <p className="text-slate-300 text-sm mt-1">Line 78: "a important document" should be "an important document" - Vowel sound mismatch</p>
                                                    </div>
                                                    <div className="bg-red-900 bg-opacity-20 border border-red-700 rounded-lg p-4">
                                                            <p className="text-red-300 font-semibold">Excessive Passive Voice</p>
                                                            <p className="text-slate-300 text-sm mt-1">Line 156: Multiple passive constructions detected - Reduce passive voice usage</p>
                                                    </div>
                                                    <div className="bg-orange-900 bg-opacity-20 border border-orange-700 rounded-lg p-4">
                                                            <p className="text-orange-300 font-semibold">Article Consistency</p>
                                                            <p className="text-slate-300 text-sm mt-1">Line 34: "an database" should be "a database" - Consonant sound requires "a"</p>
                                                    </div>
                                            </div>
                                    </div>

                                    {/* Download Section */}
                                    <div className="border-t border-slate-700 pt-8">
                                            <h3 className="text-lg font-semibold text-white mb-4">Export Report</h3>
                                            <div className="flex gap-4">
                                                    <button 
                                                        onClick={handleDownloadPDF}
                                                        className="flex-1 bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-6 rounded-lg transition duration-200 flex items-center justify-center gap-2">
                                                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8m0 8l-4-2m4 2l4-2" />
                                                            </svg>
                                                            Download PDF
                                                    </button>
                                                    <button 
                                                        onClick={handleDownloadCSV}
                                                        className="flex-1 bg-green-600 hover:bg-green-700 text-white font-semibold py-3 px-6 rounded-lg transition duration-200 flex items-center justify-center gap-2">
                                                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8m0 8l-4-2m4 2l4-2" />
                                                            </svg>
                                                            Export CSV
                                                    </button>
                                            </div>
                                    </div>
                            </div>

                            {/* Action Buttons */}
                            <div className="flex gap-4">
                                    <button 
                                        onClick={handleStartNewAnalysis}
                                        className="flex-1 bg-slate-700 hover:bg-slate-600 text-white font-semibold py-3 px-6 rounded-lg transition duration-200">
                                            Start New Analysis
                                    </button>
                                    <button 
                                        onClick={handleBackToChat}
                                        className="flex-1 bg-slate-700 hover:bg-slate-600 text-white font-semibold py-3 px-6 rounded-lg transition duration-200">
                                            Back to Chat
                                    </button>
                            </div>
                    </div>
            </div>
    </>
    )
}

export default GeneratedReport